import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Menu } from '../types/typings';

const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title> Next JS App </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
      <h1> Hello World </h1>
      </div>

    </div>
  )
}

export default Home
